"""Central path resolution for the GlassBox-NR runnable package.

Every kernel/backend module that used to locate its sibling modules and data
files via `sys.path.insert` against internal round-directory names now
resolves them through this module instead. This file only computes paths and
builds the sys.path list -- it does not decide whether any of those paths
exist, and it does not gate access to them; a module that reads a file this
points at will get the interpreter's own FileNotFoundError if that file
isn't there yet (e.g. the SASS-dependent B70/S157 paths, pending a decision
on the SASS-dependency question -- see DESIGN_ZH.md section 3.5).
"""
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2026 GlassBox-NR contributors

from pathlib import Path

PKG_ROOT = Path(__file__).resolve().parent.parent

# --- kernel subpackages (glassbox_nr/kernels/<name>/) ---
KERNELS = PKG_ROOT / "glassbox_nr" / "kernels"
CORE_DIR = KERNELS / "core"
ENCODER_WINDOWS_DIR = KERNELS / "encoder_windows"
SPLIT16_COMMON_DIR = KERNELS / "split16_common"
SPLIT16_R02_DIR = KERNELS / "split16_r02"
SPLIT16_R03_DIR = KERNELS / "split16_r03"
SPLIT16_R04_DIR = KERNELS / "split16_r04"
SPLIT16_R05_DIR = KERNELS / "split16_r05"
SPLIT16_R06_DIR = KERNELS / "split16_r06"
SPLIT16_R07_DIR = KERNELS / "split16_r07"
VIT_DIR = KERNELS / "vit"
B39_DIR = KERNELS / "b39"
TRANSITIONS_DIR = KERNELS / "transitions"
LUNA_DIR = KERNELS / "luna"
B63_S157_DIR = KERNELS / "b63_s157"
B66_DIR = KERNELS / "b66"
B6X_DIR = KERNELS / "b6x"

# B70/S157's own exit-point chain and the SASS text files they parse are not
# migrated pending the SASS-dependency decision (DESIGN_ZH.md 3.5). This
# points at where they would live if/when that is resolved; nothing reads it
# unless the B70 or S157 branch actually runs.
SASS_DIR = PKG_ROOT / "data" / "sass"

# --- data (glassbox_nr/../data/) ---
DATA_DIR = PKG_ROOT / "data"
MAPS_DIR = DATA_DIR / "maps"
TABLES_DIR = DATA_DIR / "tables"
PARAMS_DIR = DATA_DIR / "params"
VIT_B32_B38_DATA_DIR = MAPS_DIR / "vit_b32_b38"  # identity/, maps/, weights/ subtrees for the B31-B38/L99 VIT family; see map_record.py, which points its own ROUND constant at this same directory

# --- local weights, generated by tools/extract_weights.py from the user's
# own DLL; never shipped in the package ---
WEIGHTS_DIR = PKG_ROOT / "weights"
WEIGHTS_LOGICAL_FILE = WEIGHTS_DIR / "dlssnr-weights-logical.safetensors"
WEIGHTS_PACKED_FILE = WEIGHTS_DIR / "weights-packed.safetensors"
B39_WEIGHT_SLICE_FILE = WEIGHTS_DIR / "block39.layer0.layer.bin"  # see release/_private/weight_derived_files.json

# --- node registry: static declaration of the 73-node graph (stage, launch
# function name, declared inputs/outputs, sha of the predictor module that
# implements it) -- derived from the project's own nodes.json by
# packaging derivation tools (see release/p2-runnable/tools/), preserving
# declared_injection structure; see DATA_DIR/nodes.json's sibling
# provenance entry in data/maps/PROVENANCE.md ---
NODES_JSON = DATA_DIR / "nodes.json"

# --- sample capture inputs, generated locally by glassbox_nr/s0_grand.py
# from the user's own capture package (see its module docstring); raw
# capture data is never shipped in the package ---
ANCHORS_DIR = PKG_ROOT / "anchors"

# --- module search path entries every kernel module needs on sys.path for
# its own bare `import <module>` statements to resolve ---
SYS_PATH_ENTRIES = [
    str(PKG_ROOT),                # for `glassbox_nr.*` / `third_party.*` dotted imports
    str(PKG_ROOT / "glassbox_nr"),  # for bare `import s0_grand` (framework-level sibling of node_executor.py)
    str(ENCODER_WINDOWS_DIR),
    str(SPLIT16_COMMON_DIR),
    str(SPLIT16_R03_DIR),         # arith2 as A2 (grand dispatcher's own top-level import) resolves from here, matching the original round's choice of R03 specifically
    str(VIT_DIR),
    str(B39_DIR),
    str(TRANSITIONS_DIR),
    str(B63_S157_DIR),
    str(LUNA_DIR),
]
